name: Build and Push Docker Image for Kitty-cash-mock

on:
  push:
    branches:
      - main  # Déclenche le workflow sur les pushs dans la branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout le code source de votre dépôt
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configurer Docker pour l'action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login à Docker Hub pour push l'image
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Configuré dans les secrets du repo
          password: ${{ secrets.DOCKER_PASSWORD }}  # Configuré dans les secrets du repo

      # Construire l'image Docker et taguer avec la dernière version de Git
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .  # Contexte du Dockerfile
          push: true  # Push l'image vers Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/mockserver-kitty-cash:latest

      - name: Deploy to VPS via ssh 🧑🏿‍💻 (Prod Environment)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /opt/kitty-cash-mock
            docker-compose pull
            docker-compose up -d

      - name: Remove unused Docker images and volumes 🗑️
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker image prune -a -f
            docker volume prune -f

